version: '3'
services:
  afourathon-app:
    build: 
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
